# Add your api keys here for the application.
# Go to the following URLs, these API keys are free and provide the necessary data.
# At the bare minimum you need at least the NewsAPI and Stock API key.

keys:
  # Newsapi.org/v2
  world_news_api_key: ''
  # Alphavantage.co
  stock_data_api_key: ''
  # TweleveData API Key
  12data: ''

reddit: # Contains the reddit api information. 
  # Client_ID is emailed to you after creating an "app" in reddit. See README for more details.
  client_id: ''
  # Client_Secret is displayed after creating an "app" in reddit. See README for more details.
  client_secret: ''
  # User_Agent is your reddit username associted with the "app" you created.
  user_agent: ''

